### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Fot3k** [Magmonix/RAWR_WotLK_3.3.5a#1]
Hi, this project looks great but there seem to be some files missing for it to all function according to your readme files?

There is no Rawr.exe file and some of the batch files missing. I've tried many Rawr versions, this seems promising since you mention updating it and adding the addon for the WoW Client.

Is it all still in development?

Thanks.

**Comment by Magmonix** [comment]
@Fot3k, let me take a look. I'm sure I just messed something up.

**Comment by Magmonix** [comment]
@Fot3k I fixed a bunch of stuff that was still broken if the data files didn't exist. I also included a set of data files that *should* just work. A .exe was included in /bin/Release but I'm not really sure if you can just run it or if you'll need to download the entire project and compile it yourself. If that's the case, I would replace the data file in your built code with the one that I've included in /bin/Release/Data (The directories and .XML files).

**Comment by Fot3k** [comment]
All working good now, thanks! I did try to compile it with your previous release but had some issues. The release in this works great. My server has some custom items, I had to remove from character for Rawr to open the XML but all is good after that. Will add those items to the DB.

Will be sharing this with my server.

Thanks for the great work!

**Comment by Fot3k** [comment]
Do you know if it's possible to add +5 stats to all items in the DB or someway to batch edit them all?

We have warforging on the server with +5 to stats and ilevel being the max upgrade.
